/* eslint-disable */
/* global __dirname */
/* generated by unstuck-webpack */
const path = require('path');
const webpack = require('webpack');
const merge = require('webpack-merge');
const { config, getBrowserEnv } = require('./webpack.config.common');
const dir_build = path.resolve(__dirname, 'dist');

module.exports = merge(config, {
  output: {
    path: dir_build,
    filename: 'bundle.dev.js',
  },
  devServer: {
    contentBase: dir_build,
    inline: true,
    port: 3000,
  },
  devtool: 'source-map',
  plugins: [
    new webpack.DefinePlugin({
      'process.env': getBrowserEnv(),
    }),
    new webpack.NoEmitOnErrorsPlugin(),
  ],
  module: {
    rules: [
      {
        test: /\.less$/,
        use: [
          'style-loader',
          'css-loader',
          {
            loader: 'postcss-loader',
            options: {
              plugins: function () {
                return [require('autoprefixer')];
              },
            },
          },
          'less-loader',
        ],
      },
    ],
  },
});
