/* eslint-disable */
/* global __dirname */
/* generated by unstuck-webpack */
const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const merge = require('webpack-merge');
const {config, getBrowserEnv} = require('./webpack.config.common');
const dir_build = path.resolve(__dirname, 'dist');

module.exports = merge(config, {
  output: {
    path: dir_build,
    filename: 'bundle.[hash].js',
  },
  plugins: [
    new CleanWebpackPlugin(['dist']),
    new ExtractTextPlugin({
      filename: 'style.[hash].css',
      allChunks: true,
    }),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production'),
        ...getBrowserEnv(),
      },
    }),
    new webpack.optimize.UglifyJsPlugin(),
  ],
  module: {
    rules: [
      {
        test: /\.less$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            'css-loader',
            {
              loader: 'postcss-loader',
              options: {
                plugins: function () {
                  return [require('autoprefixer')];
                },
              },
            },
            'less-loader',
          ],
        }),
      },
    ],
  },
});
